# hugo.toml
baseURL = "https://boyi-wang.com/"
languageCode = "en-us"
title = "BOYI WANG"
theme = "congo"

# 重要：确保正确的构建设置
publishDir = "public"
disableKinds = []

[taxonomies]
  author = "authors"

[params]
  colorScheme = "auto"
  defaultAppearance = "light"
  
  # 关键：确保主页布局设置正确
  [params.homepage]
    layout = "profile"
    showRecent = false
    showRecentItems = 0

  [params.header]
    layout = "basic"  # 或 "hamburger"
    logo = ""
    showTitle = false
    darkModeToggle = true
    searchToggle = false

  [params.footer]
    showMenu = false
    showCopyright = false
    showThemeAttribution = false
    showAppearanceSwitcher = false
    showScrollToTop = false

  [params.article]
    showDate = false
    showViews = false
    showLikes = false
    showDateUpdated = false
    showAuthor = false
    showHero = false
    heroStyle = "basic"
    showBreadcrumbs = false
    showDraftLabel = false
    showEdit = false
    editURL = ""
    editAppendPath = false
    seriesNavigation = false
    showHeadingAnchors = false
    showPagination = false
    invertPagination = false
    showReadingTime = false
    showTableOfContents = false
    showTaxonomies = false
    showAuthorsBadges = false
    showWordCount = false
    showSummary = false
    sharingLinks = false

  [params.list]
    showHero = false
    showSummary = false
    showTableOfContents = false
    showCards = false
    groupByYear = false
    cardView = false
    cardViewScreenWidth = false

  [params.sitemap]
    excludedKinds = ["taxonomy", "term"]

  [params.taxonomy]
    showTermCount = false

  [params.term]
    showHero = false
    showTableOfContents = false
    groupByYear = false
    cardView = false

  [params.author]
    name = "BOYI WANG"
    image = "avatar.jpg"
    headline = "Postdoctoral researcher @ MPI-PKS"
    bio = "Postdoc @ MPI-PKS"
    links = [
      { google-scholar = "https://scholar.google.com/citations?user=04a2hB8AAAAJ&hl=zh-CN&authuser=1&oi=sra" },
      { ResearchGate = "https://www.researchgate.net/profile/Boyi-Wang-4"},
      { orcid = "https://orcid.org/0000-0003-1107-7591" },
      { email = "mailto:boyiw@pks.mpg.de" },
      { file-pdf = "/CV_WANG.pdf" }
    ]

[menu]
  [[menu.main]]
    identifier = "cv"
    name = "CV"
    pageRef = "/cv"
    weight = 10

  [[menu.main]]
    identifier = "publications"
    name = "Publications"
    pageRef = "/publications"
    weight = 30

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true